# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# Trigger workflow for go version update on CSM projects
name: Trigger Spell Check Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    name: Trigger Spell Check in CSM-DOCS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo:
          [
            "mgandharva/test-csm-docs",
          ]

    steps:
      - name: Trigger Spell Check in CSM-DOCS
        uses: peter-evans/repository-dispatch@v3
        with:
          # For token information, see: https://github.com/peter-evans/repository-dispatch/tree/main?tab=readme-ov-file#token
          token: ${{ secrets.CSMBOT_PAT }}
          repository: ${{ matrix.repo }}
          event-type: spell-check-workflow
          client-payload: '{"ref": "refs/heads/spell-test-autofix", "sha": "${{ github.sha }}"}'
